version: '3.7'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      dockerfile: dockerfiles/development.Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=terra_mars.settings.development
    ports:
      - 8000:8000
    volumes:
      - ./terra_mars:/terra_mars
