version: '3.7'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=terra_mars.settings.development
    ports:
      - 8000:8000
    volumes:
      - ./terra_mars:/terra_mars
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
        - POSTGRES_DB=django
        - POSTGRES_USER=django
        - POSTGRES_PASSWORD=django
    volumes:
      - terra_mars_db:/var/lib/postgresql/data

volumes:
  terra_mars_db:
