version: '3.1'

services:
  terra_mars_web:
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - celery
      - celery-beat

  celery:
    build:
      context: .
    command: celery -A terra_mars worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A terra_mars beat -l info --pidfile /tmp/celerybeat.pid
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SCHEDULE_CELERY_TASKS=${SCHEDULE_CELERY_TASKS}
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
        - POSTGRES_DB=terra_mars_db
        - POSTGRES_PASSWORD=django123
        - POSTGRES_USER=django
        - MYSQL_PASSWORD=django123
    volumes:
      - terra_mars_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - terra_mars_redis:/data

volumes:
  terra_mars_db:
  terra_mars_redis:
