version: '3.7'

services:
  web:
    build:
      context: .
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
        - POSTGRES_DB=django
        - POSTGRES_USER=django
        - POSTGRES_PASSWORD=django
    volumes:
      - terra_mars_db:/var/lib/postgresql/data

volumes:
  terra_mars_db:
