version: '3.1'

services:
  terra_mars_web:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      dockerfile: docker/terra_mars_web/development.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./terra_mars:/terra_mars

  celery:
    build:
      dockerfile: docker/terra_mars_web/development.Dockerfile
    volumes:
      - ./terra_mars:/terra_mars

  celery-beat:
    build:
      dockerfile: docker/terra_mars_web/development.Dockerfile
    volumes:
      - ./terra_mars:/terra_mars
