# Generated by Django 3.0.3 on 2020-02-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CREDICOR', 'Credicor'), ('ECOLINE', 'Ecoline'), ('HELION', 'Helion'), ('MINING_GUILD', 'Mining Guild'), ('INVENTRIX', 'Inventrix'), ('INTERPLANETARY_CINEMATICS', 'Interplanetary Cinematics'), ('PHOBOLOG', 'Phobolog'), ('SATURN_SYSTEMS', 'Saturn Systems'), ('TERACTOR', 'Teractor'), ('THARSIS_REPUBLIC', 'Tharsis Republic'), ('THORGATE', 'Thorgate'), ('UNMI', 'UNMI'), ('CHEUNG_SHING_MARS', 'Cheung Shing Mars'), ('ROBINSON_INDUSTRIES', 'Robinson Industries'), ('POINT_LUNA', 'Point Luna'), ('VALLEY_TRUST', 'Valley Trust'), ('VITOR', 'Vitor'), ('ARKLIGHT', 'Arklight'), ('ARIDOR', 'Aridor'), ('POLYPHEMOS', 'Polyphemos'), ('POSEIDON', 'Poseidon'), ('STORMCRAFT_INCORPORATED', 'Stormcraft Incorporated')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('played_map', models.CharField(choices=[('Default', 'DEFAULT'), ('Hellas', 'HELLAS'), ('Elysium', 'ELYSIUM')], max_length=16)),
                ('generations_count', models.PositiveSmallIntegerField()),
                ('players_count', models.PositiveSmallIntegerField()),
                ('venus_next', models.BooleanField()),
                ('prelude', models.BooleanField()),
                ('colonies', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terraforming_rating', models.PositiveSmallIntegerField()),
                ('milestones', models.PositiveSmallIntegerField()),
                ('awards', models.PositiveSmallIntegerField()),
                ('greeneries', models.PositiveSmallIntegerField()),
                ('cities', models.PositiveSmallIntegerField()),
                ('red_cards', models.SmallIntegerField()),
                ('green_cards', models.SmallIntegerField()),
                ('blue_cards', models.SmallIntegerField()),
                ('resources', models.PositiveSmallIntegerField()),
                ('total_score', models.PositiveSmallIntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_stats', to='games.Corporation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_game_stats', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_stats', to='games.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to='games.Player'),
        ),
    ]
