# Generated by Django 3.0.7 on 2020-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_add_required_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='display_name',
            field=models.CharField(default='Corporation', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
