# Generated by Django 2.2.6 on 2019-10-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Credicor', 'CREDICOR'), ('Ecoline', 'ECOLINE'), ('Helion', 'HELION'), ('Mining Guild', 'MINING_GUILD'), ('Inventrix', 'INVENTRIX'), ('Interplanetary Cinematics', 'INTERPLANETARY_CINEMATICS'), ('Phobolog', 'PHOBOLOG'), ('Saturn Systems', 'SATURN_SYSTEMS'), ('Teractor', 'TERACTOR'), ('Tharsis Republic', 'THARSIS_REPUBLIC'), ('Thorgate', 'THORGATE'), ('UNMI', 'UNMI'), ('Cheung Shing Mars', 'CHEUNG_SHING_MARS'), ('Robinson Industries', 'ROBINSON_INDUSTRIES'), ('Point Luna', 'POINT_LUNA'), ('Valley Trust', 'VALLEY_TRUST'), ('Vitor', 'VITOR'), ('Arklight', 'ARKLIGHT'), ('Aridor', 'ARIDOR'), ('Polyphemos', 'POLYPHEMOS'), ('Poseidon', 'POSEIDON'), ('Stormcraft Incorporated', 'STORMCRAFT_INCORPORATED')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('played_map', models.CharField(choices=[('Default', 'DEFAULT'), ('Hellas', 'HELLAS'), ('Elysium', 'Elysium')], max_length=16)),
                ('generations_count', models.PositiveSmallIntegerField()),
                ('players_count', models.PositiveSmallIntegerField()),
                ('venus_next', models.BooleanField()),
                ('prelude', models.BooleanField()),
                ('colonies', models.BooleanField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to='games.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terraforming_rating', models.PositiveSmallIntegerField()),
                ('milestones', models.PositiveSmallIntegerField()),
                ('greeneries', models.PositiveSmallIntegerField()),
                ('cities', models.PositiveSmallIntegerField()),
                ('red_cards', models.PositiveSmallIntegerField()),
                ('green_cards', models.PositiveSmallIntegerField()),
                ('blue_cards', models.PositiveSmallIntegerField()),
                ('resources', models.PositiveSmallIntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_stats', to='games.Corporation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_game_stats', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_stats', to='games.Player')),
            ],
        ),
    ]
