# Generated by Django 2.2.6 on 2019-10-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_corporation_game_playergamestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_map',
            field=models.CharField(choices=[('Default', 'DEFAULT'), ('Hellas', 'HELLAS'), ('Elysium', 'ELYSIUM')], max_length=16),
        ),
    ]
