# Generated by Django 2.2.6 on 2019-10-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20191023_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(choices=[('CREDICOR', 'Credicor'), ('ECOLINE', 'Ecoline'), ('HELION', 'Helion'), ('MINING_GUILD', 'Mining Guild'), ('INVENTRIX', 'Inventrix'), ('INTERPLANETARY_CINEMATICS', 'Interplanetary Cinematics'), ('PHOBOLOG', 'Phobolog'), ('SATURN_SYSTEMS', 'Saturn Systems'), ('TERACTOR', 'Teractor'), ('THARSIS_REPUBLIC', 'Tharsis Republic'), ('THORGATE', 'Thorgate'), ('UNMI', 'UNMI'), ('CHEUNG_SHING_MARS', 'Cheung Shing Mars'), ('ROBINSON_INDUSTRIES', 'Robinson Industries'), ('POINT_LUNA', 'Point Luna'), ('VALLEY_TRUST', 'Valley Trust'), ('VITOR', 'Vitor'), ('ARKLIGHT', 'Arklight'), ('ARIDOR', 'Aridor'), ('POLYPHEMOS', 'Polyphemos'), ('POSEIDON', 'Poseidon'), ('STORMCRAFT_INCORPORATED', 'Stormcraft Incorporated')], max_length=32),
        ),
    ]
