# Generated by Django 2.2.6 on 2019-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191024_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestats',
            name='blue_cards',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='green_cards',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='red_cards',
            field=models.SmallIntegerField(),
        ),
    ]
