# Generated by Django 2.2.6 on 2019-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20191102_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='awards',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
