# Generated by Django 2.2.6 on 2019-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20191106_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='display_name',
            field=models.CharField(max_length=32),
        ),
    ]
